# Generated by Django 4.2.4 on 2023-08-12 07:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.CharField(db_index=True, default=core.models.generate_random_string, editable=False, max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='File ID')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('length', models.BigIntegerField(default=-1, verbose_name='File Length')),
                ('offset', models.BigIntegerField(default=0, verbose_name='Offset')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('tmp_path', models.CharField(max_length=4096, null=True, verbose_name='Temporary Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
