# Generated by Django 4.2.4 on 2023-08-21 11:28

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_s3object'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3object',
            name='file',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
