# Generated by Django 4.2.4 on 2023-08-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_s3object_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3object',
            name='image',
        ),
        migrations.RemoveField(
            model_name='s3object',
            name='raw_file',
        ),
        migrations.RemoveField(
            model_name='s3object',
            name='video',
        ),
    ]
