# Generated by Django 3.2.16 on 2023-01-28 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TusFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='GUID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('length', models.BigIntegerField(default=-1)),
                ('offset', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('tmp_path', models.CharField(max_length=4096, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Tus File',
                'verbose_name_plural': 'Tus Files',
                'ordering': ['-id'],
            },
        ),
    ]
