# Generated by Django 3.2.16 on 2023-01-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0002_initial'),
        ('django_tus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusfilemodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tusfilemodel', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tusfilemodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tusfilemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tusfilemodel', to='account.user', verbose_name='user that uploads the file'),
        ),
    ]
