# Generated by Django 3.2.16 on 2023-01-30 18:41

from django.db import migrations, models
import django_tus.schema


class Migration(migrations.Migration):

    dependencies = [
        ('django_tus', '0002_auto_20230130_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusfilemodel',
            name='uploaded_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=django_tus.schema.get_schema_name),
        ),
    ]
